// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: musv_msg.proto

#ifndef PROTOBUF_INCLUDED_musv_5fmsg_2eproto
#define PROTOBUF_INCLUDED_musv_5fmsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_musv_5fmsg_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_musv_5fmsg_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_musv_5fmsg_2eproto();
namespace mUSV {
class RequestData;
class RequestDataDefaultTypeInternal;
extern RequestDataDefaultTypeInternal _RequestData_default_instance_;
class SensorData;
class SensorDataDefaultTypeInternal;
extern SensorDataDefaultTypeInternal _SensorData_default_instance_;
}  // namespace mUSV
namespace google {
namespace protobuf {
template<> ::mUSV::RequestData* Arena::CreateMaybeMessage<::mUSV::RequestData>(Arena*);
template<> ::mUSV::SensorData* Arena::CreateMaybeMessage<::mUSV::SensorData>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace mUSV {

// ===================================================================

class RequestData :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mUSV.RequestData) */ {
 public:
  RequestData();
  virtual ~RequestData();

  RequestData(const RequestData& from);

  inline RequestData& operator=(const RequestData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RequestData(RequestData&& from) noexcept
    : RequestData() {
    *this = ::std::move(from);
  }

  inline RequestData& operator=(RequestData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const RequestData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RequestData* internal_default_instance() {
    return reinterpret_cast<const RequestData*>(
               &_RequestData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(RequestData* other);
  friend void swap(RequestData& a, RequestData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RequestData* New() const final {
    return CreateMaybeMessage<RequestData>(nullptr);
  }

  RequestData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RequestData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RequestData& from);
  void MergeFrom(const RequestData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 tag_id = 1;
  void clear_tag_id();
  static const int kTagIdFieldNumber = 1;
  ::google::protobuf::int32 tag_id() const;
  void set_tag_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:mUSV.RequestData)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 tag_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_musv_5fmsg_2eproto;
};
// -------------------------------------------------------------------

class SensorData :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mUSV.SensorData) */ {
 public:
  SensorData();
  virtual ~SensorData();

  SensorData(const SensorData& from);

  inline SensorData& operator=(const SensorData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SensorData(SensorData&& from) noexcept
    : SensorData() {
    *this = ::std::move(from);
  }

  inline SensorData& operator=(SensorData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const SensorData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SensorData* internal_default_instance() {
    return reinterpret_cast<const SensorData*>(
               &_SensorData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(SensorData* other);
  friend void swap(SensorData& a, SensorData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SensorData* New() const final {
    return CreateMaybeMessage<SensorData>(nullptr);
  }

  SensorData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SensorData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SensorData& from);
  void MergeFrom(const SensorData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SensorData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 obstacle_sensors = 4 [packed = true];
  int obstacle_sensors_size() const;
  void clear_obstacle_sensors();
  static const int kObstacleSensorsFieldNumber = 4;
  ::google::protobuf::int32 obstacle_sensors(int index) const;
  void set_obstacle_sensors(int index, ::google::protobuf::int32 value);
  void add_obstacle_sensors(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      obstacle_sensors() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_obstacle_sensors();

  // repeated int32 puck_sensors = 5 [packed = true];
  int puck_sensors_size() const;
  void clear_puck_sensors();
  static const int kPuckSensorsFieldNumber = 5;
  ::google::protobuf::int32 puck_sensors(int index) const;
  void set_puck_sensors(int index, ::google::protobuf::int32 value);
  void add_puck_sensors(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      puck_sensors() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_puck_sensors();

  // .google.protobuf.Timestamp last_updated = 6;
  bool has_last_updated() const;
  void clear_last_updated();
  static const int kLastUpdatedFieldNumber = 6;
  const ::google::protobuf::Timestamp& last_updated() const;
  ::google::protobuf::Timestamp* release_last_updated();
  ::google::protobuf::Timestamp* mutable_last_updated();
  void set_allocated_last_updated(::google::protobuf::Timestamp* last_updated);

  // float pose_x = 1;
  void clear_pose_x();
  static const int kPoseXFieldNumber = 1;
  float pose_x() const;
  void set_pose_x(float value);

  // float pose_y = 2;
  void clear_pose_y();
  static const int kPoseYFieldNumber = 2;
  float pose_y() const;
  void set_pose_y(float value);

  // float pose_yaw = 3;
  void clear_pose_yaw();
  static const int kPoseYawFieldNumber = 3;
  float pose_yaw() const;
  void set_pose_yaw(float value);

  // @@protoc_insertion_point(class_scope:mUSV.SensorData)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > obstacle_sensors_;
  mutable std::atomic<int> _obstacle_sensors_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > puck_sensors_;
  mutable std::atomic<int> _puck_sensors_cached_byte_size_;
  ::google::protobuf::Timestamp* last_updated_;
  float pose_x_;
  float pose_y_;
  float pose_yaw_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_musv_5fmsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RequestData

// int32 tag_id = 1;
inline void RequestData::clear_tag_id() {
  tag_id_ = 0;
}
inline ::google::protobuf::int32 RequestData::tag_id() const {
  // @@protoc_insertion_point(field_get:mUSV.RequestData.tag_id)
  return tag_id_;
}
inline void RequestData::set_tag_id(::google::protobuf::int32 value) {
  
  tag_id_ = value;
  // @@protoc_insertion_point(field_set:mUSV.RequestData.tag_id)
}

// -------------------------------------------------------------------

// SensorData

// float pose_x = 1;
inline void SensorData::clear_pose_x() {
  pose_x_ = 0;
}
inline float SensorData::pose_x() const {
  // @@protoc_insertion_point(field_get:mUSV.SensorData.pose_x)
  return pose_x_;
}
inline void SensorData::set_pose_x(float value) {
  
  pose_x_ = value;
  // @@protoc_insertion_point(field_set:mUSV.SensorData.pose_x)
}

// float pose_y = 2;
inline void SensorData::clear_pose_y() {
  pose_y_ = 0;
}
inline float SensorData::pose_y() const {
  // @@protoc_insertion_point(field_get:mUSV.SensorData.pose_y)
  return pose_y_;
}
inline void SensorData::set_pose_y(float value) {
  
  pose_y_ = value;
  // @@protoc_insertion_point(field_set:mUSV.SensorData.pose_y)
}

// float pose_yaw = 3;
inline void SensorData::clear_pose_yaw() {
  pose_yaw_ = 0;
}
inline float SensorData::pose_yaw() const {
  // @@protoc_insertion_point(field_get:mUSV.SensorData.pose_yaw)
  return pose_yaw_;
}
inline void SensorData::set_pose_yaw(float value) {
  
  pose_yaw_ = value;
  // @@protoc_insertion_point(field_set:mUSV.SensorData.pose_yaw)
}

// repeated int32 obstacle_sensors = 4 [packed = true];
inline int SensorData::obstacle_sensors_size() const {
  return obstacle_sensors_.size();
}
inline void SensorData::clear_obstacle_sensors() {
  obstacle_sensors_.Clear();
}
inline ::google::protobuf::int32 SensorData::obstacle_sensors(int index) const {
  // @@protoc_insertion_point(field_get:mUSV.SensorData.obstacle_sensors)
  return obstacle_sensors_.Get(index);
}
inline void SensorData::set_obstacle_sensors(int index, ::google::protobuf::int32 value) {
  obstacle_sensors_.Set(index, value);
  // @@protoc_insertion_point(field_set:mUSV.SensorData.obstacle_sensors)
}
inline void SensorData::add_obstacle_sensors(::google::protobuf::int32 value) {
  obstacle_sensors_.Add(value);
  // @@protoc_insertion_point(field_add:mUSV.SensorData.obstacle_sensors)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SensorData::obstacle_sensors() const {
  // @@protoc_insertion_point(field_list:mUSV.SensorData.obstacle_sensors)
  return obstacle_sensors_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SensorData::mutable_obstacle_sensors() {
  // @@protoc_insertion_point(field_mutable_list:mUSV.SensorData.obstacle_sensors)
  return &obstacle_sensors_;
}

// repeated int32 puck_sensors = 5 [packed = true];
inline int SensorData::puck_sensors_size() const {
  return puck_sensors_.size();
}
inline void SensorData::clear_puck_sensors() {
  puck_sensors_.Clear();
}
inline ::google::protobuf::int32 SensorData::puck_sensors(int index) const {
  // @@protoc_insertion_point(field_get:mUSV.SensorData.puck_sensors)
  return puck_sensors_.Get(index);
}
inline void SensorData::set_puck_sensors(int index, ::google::protobuf::int32 value) {
  puck_sensors_.Set(index, value);
  // @@protoc_insertion_point(field_set:mUSV.SensorData.puck_sensors)
}
inline void SensorData::add_puck_sensors(::google::protobuf::int32 value) {
  puck_sensors_.Add(value);
  // @@protoc_insertion_point(field_add:mUSV.SensorData.puck_sensors)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SensorData::puck_sensors() const {
  // @@protoc_insertion_point(field_list:mUSV.SensorData.puck_sensors)
  return puck_sensors_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SensorData::mutable_puck_sensors() {
  // @@protoc_insertion_point(field_mutable_list:mUSV.SensorData.puck_sensors)
  return &puck_sensors_;
}

// .google.protobuf.Timestamp last_updated = 6;
inline bool SensorData::has_last_updated() const {
  return this != internal_default_instance() && last_updated_ != nullptr;
}
inline const ::google::protobuf::Timestamp& SensorData::last_updated() const {
  const ::google::protobuf::Timestamp* p = last_updated_;
  // @@protoc_insertion_point(field_get:mUSV.SensorData.last_updated)
  return p != nullptr ? *p : *reinterpret_cast<const ::google::protobuf::Timestamp*>(
      &::google::protobuf::_Timestamp_default_instance_);
}
inline ::google::protobuf::Timestamp* SensorData::release_last_updated() {
  // @@protoc_insertion_point(field_release:mUSV.SensorData.last_updated)
  
  ::google::protobuf::Timestamp* temp = last_updated_;
  last_updated_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* SensorData::mutable_last_updated() {
  
  if (last_updated_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::protobuf::Timestamp>(GetArenaNoVirtual());
    last_updated_ = p;
  }
  // @@protoc_insertion_point(field_mutable:mUSV.SensorData.last_updated)
  return last_updated_;
}
inline void SensorData::set_allocated_last_updated(::google::protobuf::Timestamp* last_updated) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(last_updated_);
  }
  if (last_updated) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(last_updated)->GetArena();
    if (message_arena != submessage_arena) {
      last_updated = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, last_updated, submessage_arena);
    }
    
  } else {
    
  }
  last_updated_ = last_updated;
  // @@protoc_insertion_point(field_set_allocated:mUSV.SensorData.last_updated)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mUSV

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_musv_5fmsg_2eproto
