// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: musv_msg.proto

#include "musv_msg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2ftimestamp_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Timestamp_google_2fprotobuf_2ftimestamp_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_musv_5fmsg_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SensorData_ClusterPoint_musv_5fmsg_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_musv_5fmsg_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SensorData_Pose2D_musv_5fmsg_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_musv_5fmsg_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SensorData_Waypoint_musv_5fmsg_2eproto;
namespace mUSV {
class RequestDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RequestData> _instance;
} _RequestData_default_instance_;
class SensorData_Pose2DDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SensorData_Pose2D> _instance;
} _SensorData_Pose2D_default_instance_;
class SensorData_WaypointDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SensorData_Waypoint> _instance;
} _SensorData_Waypoint_default_instance_;
class SensorData_ClusterPointDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SensorData_ClusterPoint> _instance;
} _SensorData_ClusterPoint_default_instance_;
class SensorDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SensorData> _instance;
} _SensorData_default_instance_;
}  // namespace mUSV
static void InitDefaultsRequestData_musv_5fmsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mUSV::_RequestData_default_instance_;
    new (ptr) ::mUSV::RequestData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mUSV::RequestData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RequestData_musv_5fmsg_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRequestData_musv_5fmsg_2eproto}, {}};

static void InitDefaultsSensorData_Pose2D_musv_5fmsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mUSV::_SensorData_Pose2D_default_instance_;
    new (ptr) ::mUSV::SensorData_Pose2D();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mUSV::SensorData_Pose2D::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SensorData_Pose2D_musv_5fmsg_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSensorData_Pose2D_musv_5fmsg_2eproto}, {}};

static void InitDefaultsSensorData_Waypoint_musv_5fmsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mUSV::_SensorData_Waypoint_default_instance_;
    new (ptr) ::mUSV::SensorData_Waypoint();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mUSV::SensorData_Waypoint::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SensorData_Waypoint_musv_5fmsg_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSensorData_Waypoint_musv_5fmsg_2eproto}, {}};

static void InitDefaultsSensorData_ClusterPoint_musv_5fmsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mUSV::_SensorData_ClusterPoint_default_instance_;
    new (ptr) ::mUSV::SensorData_ClusterPoint();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mUSV::SensorData_ClusterPoint::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SensorData_ClusterPoint_musv_5fmsg_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSensorData_ClusterPoint_musv_5fmsg_2eproto}, {}};

static void InitDefaultsSensorData_musv_5fmsg_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mUSV::_SensorData_default_instance_;
    new (ptr) ::mUSV::SensorData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mUSV::SensorData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<4> scc_info_SensorData_musv_5fmsg_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 4, InitDefaultsSensorData_musv_5fmsg_2eproto}, {
      &scc_info_SensorData_Pose2D_musv_5fmsg_2eproto.base,
      &scc_info_Timestamp_google_2fprotobuf_2ftimestamp_2eproto.base,
      &scc_info_SensorData_Waypoint_musv_5fmsg_2eproto.base,
      &scc_info_SensorData_ClusterPoint_musv_5fmsg_2eproto.base,}};

void InitDefaults_musv_5fmsg_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_RequestData_musv_5fmsg_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SensorData_Pose2D_musv_5fmsg_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SensorData_Waypoint_musv_5fmsg_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SensorData_ClusterPoint_musv_5fmsg_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SensorData_musv_5fmsg_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_musv_5fmsg_2eproto[5];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_musv_5fmsg_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_musv_5fmsg_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_musv_5fmsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mUSV::RequestData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mUSV::RequestData, tag_id_),
  PROTOBUF_FIELD_OFFSET(::mUSV::RequestData, request_waypoints_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData_Pose2D, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData_Pose2D, x_),
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData_Pose2D, y_),
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData_Pose2D, yaw_),
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData_Pose2D, xpx_),
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData_Pose2D, ypx_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData_Waypoint, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData_Waypoint, x_),
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData_Waypoint, y_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData_ClusterPoint, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData_ClusterPoint, range_),
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData_ClusterPoint, heading_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData, pose_),
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData, obstacle_sensors_),
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData, target_sensors_),
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData, timestamp_),
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData, waypoints_),
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData, loop_waypoints_),
  PROTOBUF_FIELD_OFFSET(::mUSV::SensorData, clusterpoint_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::mUSV::RequestData)},
  { 7, -1, sizeof(::mUSV::SensorData_Pose2D)},
  { 17, -1, sizeof(::mUSV::SensorData_Waypoint)},
  { 24, -1, sizeof(::mUSV::SensorData_ClusterPoint)},
  { 31, -1, sizeof(::mUSV::SensorData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::mUSV::_RequestData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mUSV::_SensorData_Pose2D_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mUSV::_SensorData_Waypoint_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mUSV::_SensorData_ClusterPoint_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mUSV::_SensorData_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_musv_5fmsg_2eproto = {
  {}, AddDescriptors_musv_5fmsg_2eproto, "musv_msg.proto", schemas,
  file_default_instances, TableStruct_musv_5fmsg_2eproto::offsets,
  file_level_metadata_musv_5fmsg_2eproto, 5, file_level_enum_descriptors_musv_5fmsg_2eproto, file_level_service_descriptors_musv_5fmsg_2eproto,
};

const char descriptor_table_protodef_musv_5fmsg_2eproto[] =
  "\n\016musv_msg.proto\022\004mUSV\032\037google/protobuf/"
  "timestamp.proto\"8\n\013RequestData\022\016\n\006tag_id"
  "\030\001 \001(\005\022\031\n\021request_waypoints\030\002 \001(\010\"\260\003\n\nSe"
  "nsorData\022%\n\004pose\030\001 \001(\0132\027.mUSV.SensorData"
  ".Pose2D\022\034\n\020obstacle_sensors\030\002 \003(\005B\002\020\001\022\032\n"
  "\016target_sensors\030\003 \003(\005B\002\020\001\022-\n\ttimestamp\030\004"
  " \001(\0132\032.google.protobuf.Timestamp\022,\n\twayp"
  "oints\030\005 \003(\0132\031.mUSV.SensorData.Waypoint\022\026"
  "\n\016loop_waypoints\030\006 \001(\010\0223\n\014clusterPoint\030\007"
  " \001(\0132\035.mUSV.SensorData.ClusterPoint\032E\n\006P"
  "ose2D\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\013\n\003yaw\030\003 \001(\002"
  "\022\013\n\003xpx\030\004 \001(\005\022\013\n\003ypx\030\005 \001(\005\032 \n\010Waypoint\022\t"
  "\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\032.\n\014ClusterPoint\022\r\n\005"
  "range\030\001 \001(\002\022\017\n\007heading\030\002 \001(\002b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_musv_5fmsg_2eproto = {
  false, InitDefaults_musv_5fmsg_2eproto, 
  descriptor_table_protodef_musv_5fmsg_2eproto,
  "musv_msg.proto", &assign_descriptors_table_musv_5fmsg_2eproto, 556,
};

void AddDescriptors_musv_5fmsg_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_google_2fprotobuf_2ftimestamp_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_musv_5fmsg_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_musv_5fmsg_2eproto = []() { AddDescriptors_musv_5fmsg_2eproto(); return true; }();
namespace mUSV {

// ===================================================================

void RequestData::InitAsDefaultInstance() {
}
class RequestData::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RequestData::kTagIdFieldNumber;
const int RequestData::kRequestWaypointsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RequestData::RequestData()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mUSV.RequestData)
}
RequestData::RequestData(const RequestData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&tag_id_, &from.tag_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&request_waypoints_) -
    reinterpret_cast<char*>(&tag_id_)) + sizeof(request_waypoints_));
  // @@protoc_insertion_point(copy_constructor:mUSV.RequestData)
}

void RequestData::SharedCtor() {
  ::memset(&tag_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&request_waypoints_) -
      reinterpret_cast<char*>(&tag_id_)) + sizeof(request_waypoints_));
}

RequestData::~RequestData() {
  // @@protoc_insertion_point(destructor:mUSV.RequestData)
  SharedDtor();
}

void RequestData::SharedDtor() {
}

void RequestData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RequestData& RequestData::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_RequestData_musv_5fmsg_2eproto.base);
  return *internal_default_instance();
}


void RequestData::Clear() {
// @@protoc_insertion_point(message_clear_start:mUSV.RequestData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&tag_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&request_waypoints_) -
      reinterpret_cast<char*>(&tag_id_)) + sizeof(request_waypoints_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* RequestData::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<RequestData*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 tag_id = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_tag_id(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // bool request_waypoints = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_request_waypoints(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool RequestData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mUSV.RequestData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 tag_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &tag_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool request_waypoints = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &request_waypoints_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mUSV.RequestData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mUSV.RequestData)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void RequestData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mUSV.RequestData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 tag_id = 1;
  if (this->tag_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->tag_id(), output);
  }

  // bool request_waypoints = 2;
  if (this->request_waypoints() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->request_waypoints(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mUSV.RequestData)
}

::google::protobuf::uint8* RequestData::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:mUSV.RequestData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 tag_id = 1;
  if (this->tag_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->tag_id(), target);
  }

  // bool request_waypoints = 2;
  if (this->request_waypoints() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->request_waypoints(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mUSV.RequestData)
  return target;
}

size_t RequestData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mUSV.RequestData)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 tag_id = 1;
  if (this->tag_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->tag_id());
  }

  // bool request_waypoints = 2;
  if (this->request_waypoints() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RequestData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mUSV.RequestData)
  GOOGLE_DCHECK_NE(&from, this);
  const RequestData* source =
      ::google::protobuf::DynamicCastToGenerated<RequestData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mUSV.RequestData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mUSV.RequestData)
    MergeFrom(*source);
  }
}

void RequestData::MergeFrom(const RequestData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mUSV.RequestData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.tag_id() != 0) {
    set_tag_id(from.tag_id());
  }
  if (from.request_waypoints() != 0) {
    set_request_waypoints(from.request_waypoints());
  }
}

void RequestData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mUSV.RequestData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RequestData::CopyFrom(const RequestData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mUSV.RequestData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestData::IsInitialized() const {
  return true;
}

void RequestData::Swap(RequestData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RequestData::InternalSwap(RequestData* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(tag_id_, other->tag_id_);
  swap(request_waypoints_, other->request_waypoints_);
}

::google::protobuf::Metadata RequestData::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_musv_5fmsg_2eproto);
  return ::file_level_metadata_musv_5fmsg_2eproto[kIndexInFileMessages];
}


// ===================================================================

void SensorData_Pose2D::InitAsDefaultInstance() {
}
class SensorData_Pose2D::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SensorData_Pose2D::kXFieldNumber;
const int SensorData_Pose2D::kYFieldNumber;
const int SensorData_Pose2D::kYawFieldNumber;
const int SensorData_Pose2D::kXpxFieldNumber;
const int SensorData_Pose2D::kYpxFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SensorData_Pose2D::SensorData_Pose2D()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mUSV.SensorData.Pose2D)
}
SensorData_Pose2D::SensorData_Pose2D(const SensorData_Pose2D& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&ypx_) -
    reinterpret_cast<char*>(&x_)) + sizeof(ypx_));
  // @@protoc_insertion_point(copy_constructor:mUSV.SensorData.Pose2D)
}

void SensorData_Pose2D::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ypx_) -
      reinterpret_cast<char*>(&x_)) + sizeof(ypx_));
}

SensorData_Pose2D::~SensorData_Pose2D() {
  // @@protoc_insertion_point(destructor:mUSV.SensorData.Pose2D)
  SharedDtor();
}

void SensorData_Pose2D::SharedDtor() {
}

void SensorData_Pose2D::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SensorData_Pose2D& SensorData_Pose2D::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_SensorData_Pose2D_musv_5fmsg_2eproto.base);
  return *internal_default_instance();
}


void SensorData_Pose2D::Clear() {
// @@protoc_insertion_point(message_clear_start:mUSV.SensorData.Pose2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ypx_) -
      reinterpret_cast<char*>(&x_)) + sizeof(ypx_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* SensorData_Pose2D::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<SensorData_Pose2D*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // float x = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 13) goto handle_unusual;
        msg->set_x(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float y = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 21) goto handle_unusual;
        msg->set_y(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float yaw = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 29) goto handle_unusual;
        msg->set_yaw(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // int32 xpx = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 32) goto handle_unusual;
        msg->set_xpx(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // int32 ypx = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 40) goto handle_unusual;
        msg->set_ypx(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool SensorData_Pose2D::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mUSV.SensorData.Pose2D)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (13 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (21 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float yaw = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (29 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &yaw_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 xpx = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (32 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &xpx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 ypx = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (40 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ypx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mUSV.SensorData.Pose2D)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mUSV.SensorData.Pose2D)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void SensorData_Pose2D::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mUSV.SensorData.Pose2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  // float yaw = 3;
  if (this->yaw() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->yaw(), output);
  }

  // int32 xpx = 4;
  if (this->xpx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->xpx(), output);
  }

  // int32 ypx = 5;
  if (this->ypx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->ypx(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mUSV.SensorData.Pose2D)
}

::google::protobuf::uint8* SensorData_Pose2D::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:mUSV.SensorData.Pose2D)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  // float yaw = 3;
  if (this->yaw() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->yaw(), target);
  }

  // int32 xpx = 4;
  if (this->xpx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->xpx(), target);
  }

  // int32 ypx = 5;
  if (this->ypx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->ypx(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mUSV.SensorData.Pose2D)
  return target;
}

size_t SensorData_Pose2D::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mUSV.SensorData.Pose2D)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // float yaw = 3;
  if (this->yaw() != 0) {
    total_size += 1 + 4;
  }

  // int32 xpx = 4;
  if (this->xpx() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->xpx());
  }

  // int32 ypx = 5;
  if (this->ypx() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->ypx());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SensorData_Pose2D::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mUSV.SensorData.Pose2D)
  GOOGLE_DCHECK_NE(&from, this);
  const SensorData_Pose2D* source =
      ::google::protobuf::DynamicCastToGenerated<SensorData_Pose2D>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mUSV.SensorData.Pose2D)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mUSV.SensorData.Pose2D)
    MergeFrom(*source);
  }
}

void SensorData_Pose2D::MergeFrom(const SensorData_Pose2D& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mUSV.SensorData.Pose2D)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.yaw() != 0) {
    set_yaw(from.yaw());
  }
  if (from.xpx() != 0) {
    set_xpx(from.xpx());
  }
  if (from.ypx() != 0) {
    set_ypx(from.ypx());
  }
}

void SensorData_Pose2D::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mUSV.SensorData.Pose2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SensorData_Pose2D::CopyFrom(const SensorData_Pose2D& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mUSV.SensorData.Pose2D)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SensorData_Pose2D::IsInitialized() const {
  return true;
}

void SensorData_Pose2D::Swap(SensorData_Pose2D* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SensorData_Pose2D::InternalSwap(SensorData_Pose2D* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(yaw_, other->yaw_);
  swap(xpx_, other->xpx_);
  swap(ypx_, other->ypx_);
}

::google::protobuf::Metadata SensorData_Pose2D::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_musv_5fmsg_2eproto);
  return ::file_level_metadata_musv_5fmsg_2eproto[kIndexInFileMessages];
}


// ===================================================================

void SensorData_Waypoint::InitAsDefaultInstance() {
}
class SensorData_Waypoint::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SensorData_Waypoint::kXFieldNumber;
const int SensorData_Waypoint::kYFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SensorData_Waypoint::SensorData_Waypoint()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mUSV.SensorData.Waypoint)
}
SensorData_Waypoint::SensorData_Waypoint(const SensorData_Waypoint& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&y_) -
    reinterpret_cast<char*>(&x_)) + sizeof(y_));
  // @@protoc_insertion_point(copy_constructor:mUSV.SensorData.Waypoint)
}

void SensorData_Waypoint::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_) -
      reinterpret_cast<char*>(&x_)) + sizeof(y_));
}

SensorData_Waypoint::~SensorData_Waypoint() {
  // @@protoc_insertion_point(destructor:mUSV.SensorData.Waypoint)
  SharedDtor();
}

void SensorData_Waypoint::SharedDtor() {
}

void SensorData_Waypoint::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SensorData_Waypoint& SensorData_Waypoint::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_SensorData_Waypoint_musv_5fmsg_2eproto.base);
  return *internal_default_instance();
}


void SensorData_Waypoint::Clear() {
// @@protoc_insertion_point(message_clear_start:mUSV.SensorData.Waypoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_) -
      reinterpret_cast<char*>(&x_)) + sizeof(y_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* SensorData_Waypoint::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<SensorData_Waypoint*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // float x = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 13) goto handle_unusual;
        msg->set_x(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float y = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 21) goto handle_unusual;
        msg->set_y(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool SensorData_Waypoint::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mUSV.SensorData.Waypoint)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (13 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (21 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mUSV.SensorData.Waypoint)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mUSV.SensorData.Waypoint)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void SensorData_Waypoint::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mUSV.SensorData.Waypoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mUSV.SensorData.Waypoint)
}

::google::protobuf::uint8* SensorData_Waypoint::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:mUSV.SensorData.Waypoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mUSV.SensorData.Waypoint)
  return target;
}

size_t SensorData_Waypoint::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mUSV.SensorData.Waypoint)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SensorData_Waypoint::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mUSV.SensorData.Waypoint)
  GOOGLE_DCHECK_NE(&from, this);
  const SensorData_Waypoint* source =
      ::google::protobuf::DynamicCastToGenerated<SensorData_Waypoint>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mUSV.SensorData.Waypoint)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mUSV.SensorData.Waypoint)
    MergeFrom(*source);
  }
}

void SensorData_Waypoint::MergeFrom(const SensorData_Waypoint& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mUSV.SensorData.Waypoint)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
}

void SensorData_Waypoint::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mUSV.SensorData.Waypoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SensorData_Waypoint::CopyFrom(const SensorData_Waypoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mUSV.SensorData.Waypoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SensorData_Waypoint::IsInitialized() const {
  return true;
}

void SensorData_Waypoint::Swap(SensorData_Waypoint* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SensorData_Waypoint::InternalSwap(SensorData_Waypoint* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(x_, other->x_);
  swap(y_, other->y_);
}

::google::protobuf::Metadata SensorData_Waypoint::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_musv_5fmsg_2eproto);
  return ::file_level_metadata_musv_5fmsg_2eproto[kIndexInFileMessages];
}


// ===================================================================

void SensorData_ClusterPoint::InitAsDefaultInstance() {
}
class SensorData_ClusterPoint::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SensorData_ClusterPoint::kRangeFieldNumber;
const int SensorData_ClusterPoint::kHeadingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SensorData_ClusterPoint::SensorData_ClusterPoint()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mUSV.SensorData.ClusterPoint)
}
SensorData_ClusterPoint::SensorData_ClusterPoint(const SensorData_ClusterPoint& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&range_, &from.range_,
    static_cast<size_t>(reinterpret_cast<char*>(&heading_) -
    reinterpret_cast<char*>(&range_)) + sizeof(heading_));
  // @@protoc_insertion_point(copy_constructor:mUSV.SensorData.ClusterPoint)
}

void SensorData_ClusterPoint::SharedCtor() {
  ::memset(&range_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&heading_) -
      reinterpret_cast<char*>(&range_)) + sizeof(heading_));
}

SensorData_ClusterPoint::~SensorData_ClusterPoint() {
  // @@protoc_insertion_point(destructor:mUSV.SensorData.ClusterPoint)
  SharedDtor();
}

void SensorData_ClusterPoint::SharedDtor() {
}

void SensorData_ClusterPoint::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SensorData_ClusterPoint& SensorData_ClusterPoint::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_SensorData_ClusterPoint_musv_5fmsg_2eproto.base);
  return *internal_default_instance();
}


void SensorData_ClusterPoint::Clear() {
// @@protoc_insertion_point(message_clear_start:mUSV.SensorData.ClusterPoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&range_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&heading_) -
      reinterpret_cast<char*>(&range_)) + sizeof(heading_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* SensorData_ClusterPoint::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<SensorData_ClusterPoint*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // float range = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 13) goto handle_unusual;
        msg->set_range(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float heading = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 21) goto handle_unusual;
        msg->set_heading(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool SensorData_ClusterPoint::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mUSV.SensorData.ClusterPoint)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float range = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (13 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &range_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float heading = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (21 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &heading_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mUSV.SensorData.ClusterPoint)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mUSV.SensorData.ClusterPoint)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void SensorData_ClusterPoint::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mUSV.SensorData.ClusterPoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float range = 1;
  if (this->range() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->range(), output);
  }

  // float heading = 2;
  if (this->heading() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->heading(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mUSV.SensorData.ClusterPoint)
}

::google::protobuf::uint8* SensorData_ClusterPoint::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:mUSV.SensorData.ClusterPoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float range = 1;
  if (this->range() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->range(), target);
  }

  // float heading = 2;
  if (this->heading() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->heading(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mUSV.SensorData.ClusterPoint)
  return target;
}

size_t SensorData_ClusterPoint::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mUSV.SensorData.ClusterPoint)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float range = 1;
  if (this->range() != 0) {
    total_size += 1 + 4;
  }

  // float heading = 2;
  if (this->heading() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SensorData_ClusterPoint::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mUSV.SensorData.ClusterPoint)
  GOOGLE_DCHECK_NE(&from, this);
  const SensorData_ClusterPoint* source =
      ::google::protobuf::DynamicCastToGenerated<SensorData_ClusterPoint>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mUSV.SensorData.ClusterPoint)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mUSV.SensorData.ClusterPoint)
    MergeFrom(*source);
  }
}

void SensorData_ClusterPoint::MergeFrom(const SensorData_ClusterPoint& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mUSV.SensorData.ClusterPoint)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.range() != 0) {
    set_range(from.range());
  }
  if (from.heading() != 0) {
    set_heading(from.heading());
  }
}

void SensorData_ClusterPoint::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mUSV.SensorData.ClusterPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SensorData_ClusterPoint::CopyFrom(const SensorData_ClusterPoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mUSV.SensorData.ClusterPoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SensorData_ClusterPoint::IsInitialized() const {
  return true;
}

void SensorData_ClusterPoint::Swap(SensorData_ClusterPoint* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SensorData_ClusterPoint::InternalSwap(SensorData_ClusterPoint* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(range_, other->range_);
  swap(heading_, other->heading_);
}

::google::protobuf::Metadata SensorData_ClusterPoint::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_musv_5fmsg_2eproto);
  return ::file_level_metadata_musv_5fmsg_2eproto[kIndexInFileMessages];
}


// ===================================================================

void SensorData::InitAsDefaultInstance() {
  ::mUSV::_SensorData_default_instance_._instance.get_mutable()->pose_ = const_cast< ::mUSV::SensorData_Pose2D*>(
      ::mUSV::SensorData_Pose2D::internal_default_instance());
  ::mUSV::_SensorData_default_instance_._instance.get_mutable()->timestamp_ = const_cast< ::google::protobuf::Timestamp*>(
      ::google::protobuf::Timestamp::internal_default_instance());
  ::mUSV::_SensorData_default_instance_._instance.get_mutable()->clusterpoint_ = const_cast< ::mUSV::SensorData_ClusterPoint*>(
      ::mUSV::SensorData_ClusterPoint::internal_default_instance());
}
class SensorData::HasBitSetters {
 public:
  static const ::mUSV::SensorData_Pose2D& pose(const SensorData* msg);
  static const ::google::protobuf::Timestamp& timestamp(const SensorData* msg);
  static const ::mUSV::SensorData_ClusterPoint& clusterpoint(const SensorData* msg);
};

const ::mUSV::SensorData_Pose2D&
SensorData::HasBitSetters::pose(const SensorData* msg) {
  return *msg->pose_;
}
const ::google::protobuf::Timestamp&
SensorData::HasBitSetters::timestamp(const SensorData* msg) {
  return *msg->timestamp_;
}
const ::mUSV::SensorData_ClusterPoint&
SensorData::HasBitSetters::clusterpoint(const SensorData* msg) {
  return *msg->clusterpoint_;
}
void SensorData::clear_timestamp() {
  if (GetArenaNoVirtual() == nullptr && timestamp_ != nullptr) {
    delete timestamp_;
  }
  timestamp_ = nullptr;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SensorData::kPoseFieldNumber;
const int SensorData::kObstacleSensorsFieldNumber;
const int SensorData::kTargetSensorsFieldNumber;
const int SensorData::kTimestampFieldNumber;
const int SensorData::kWaypointsFieldNumber;
const int SensorData::kLoopWaypointsFieldNumber;
const int SensorData::kClusterPointFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SensorData::SensorData()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mUSV.SensorData)
}
SensorData::SensorData(const SensorData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      obstacle_sensors_(from.obstacle_sensors_),
      target_sensors_(from.target_sensors_),
      waypoints_(from.waypoints_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_pose()) {
    pose_ = new ::mUSV::SensorData_Pose2D(*from.pose_);
  } else {
    pose_ = nullptr;
  }
  if (from.has_timestamp()) {
    timestamp_ = new ::google::protobuf::Timestamp(*from.timestamp_);
  } else {
    timestamp_ = nullptr;
  }
  if (from.has_clusterpoint()) {
    clusterpoint_ = new ::mUSV::SensorData_ClusterPoint(*from.clusterpoint_);
  } else {
    clusterpoint_ = nullptr;
  }
  loop_waypoints_ = from.loop_waypoints_;
  // @@protoc_insertion_point(copy_constructor:mUSV.SensorData)
}

void SensorData::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_SensorData_musv_5fmsg_2eproto.base);
  ::memset(&pose_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&loop_waypoints_) -
      reinterpret_cast<char*>(&pose_)) + sizeof(loop_waypoints_));
}

SensorData::~SensorData() {
  // @@protoc_insertion_point(destructor:mUSV.SensorData)
  SharedDtor();
}

void SensorData::SharedDtor() {
  if (this != internal_default_instance()) delete pose_;
  if (this != internal_default_instance()) delete timestamp_;
  if (this != internal_default_instance()) delete clusterpoint_;
}

void SensorData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SensorData& SensorData::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_SensorData_musv_5fmsg_2eproto.base);
  return *internal_default_instance();
}


void SensorData::Clear() {
// @@protoc_insertion_point(message_clear_start:mUSV.SensorData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  obstacle_sensors_.Clear();
  target_sensors_.Clear();
  waypoints_.Clear();
  if (GetArenaNoVirtual() == nullptr && pose_ != nullptr) {
    delete pose_;
  }
  pose_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && timestamp_ != nullptr) {
    delete timestamp_;
  }
  timestamp_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && clusterpoint_ != nullptr) {
    delete clusterpoint_;
  }
  clusterpoint_ = nullptr;
  loop_waypoints_ = false;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* SensorData::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<SensorData*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // .mUSV.SensorData.Pose2D pose = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::mUSV::SensorData_Pose2D::_InternalParse;
        object = msg->mutable_pose();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // repeated int32 obstacle_sensors = 2 [packed = true];
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) == 18) {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::PackedInt32Parser;
          object = msg->mutable_obstacle_sensors();
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          if (size) ptr = parser_till_end(ptr, newend, object, ctx);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
          break;
        } else if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        do {
          msg->add_obstacle_sensors(::google::protobuf::internal::ReadVarint(&ptr));
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 16 && (ptr += 1));
        break;
      }
      // repeated int32 target_sensors = 3 [packed = true];
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) == 26) {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::PackedInt32Parser;
          object = msg->mutable_target_sensors();
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          if (size) ptr = parser_till_end(ptr, newend, object, ctx);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
          break;
        } else if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        do {
          msg->add_target_sensors(::google::protobuf::internal::ReadVarint(&ptr));
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 24 && (ptr += 1));
        break;
      }
      // .google.protobuf.Timestamp timestamp = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::google::protobuf::Timestamp::_InternalParse;
        object = msg->mutable_timestamp();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      // repeated .mUSV.SensorData.Waypoint waypoints = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 42) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::mUSV::SensorData_Waypoint::_InternalParse;
          object = msg->add_waypoints();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 42 && (ptr += 1));
        break;
      }
      // bool loop_waypoints = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 48) goto handle_unusual;
        msg->set_loop_waypoints(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // .mUSV.SensorData.ClusterPoint clusterPoint = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 58) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        parser_till_end = ::mUSV::SensorData_ClusterPoint::_InternalParse;
        object = msg->mutable_clusterpoint();
        if (size > end - ptr) goto len_delim_till_end;
        ptr += size;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
            {parser_till_end, object}, ptr - size, ptr));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool SensorData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mUSV.SensorData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .mUSV.SensorData.Pose2D pose = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_pose()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 obstacle_sensors = 2 [packed = true];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_obstacle_sensors())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 18u, input, this->mutable_obstacle_sensors())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 target_sensors = 3 [packed = true];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_target_sensors())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 26u, input, this->mutable_target_sensors())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Timestamp timestamp = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_timestamp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .mUSV.SensorData.Waypoint waypoints = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (42 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_waypoints()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool loop_waypoints = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (48 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &loop_waypoints_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .mUSV.SensorData.ClusterPoint clusterPoint = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (58 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_clusterpoint()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mUSV.SensorData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mUSV.SensorData)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void SensorData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mUSV.SensorData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .mUSV.SensorData.Pose2D pose = 1;
  if (this->has_pose()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, HasBitSetters::pose(this), output);
  }

  // repeated int32 obstacle_sensors = 2 [packed = true];
  if (this->obstacle_sensors_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_obstacle_sensors_cached_byte_size_.load(
        std::memory_order_relaxed));
  }
  for (int i = 0, n = this->obstacle_sensors_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->obstacle_sensors(i), output);
  }

  // repeated int32 target_sensors = 3 [packed = true];
  if (this->target_sensors_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_target_sensors_cached_byte_size_.load(
        std::memory_order_relaxed));
  }
  for (int i = 0, n = this->target_sensors_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->target_sensors(i), output);
  }

  // .google.protobuf.Timestamp timestamp = 4;
  if (this->has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, HasBitSetters::timestamp(this), output);
  }

  // repeated .mUSV.SensorData.Waypoint waypoints = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->waypoints_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->waypoints(static_cast<int>(i)),
      output);
  }

  // bool loop_waypoints = 6;
  if (this->loop_waypoints() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->loop_waypoints(), output);
  }

  // .mUSV.SensorData.ClusterPoint clusterPoint = 7;
  if (this->has_clusterpoint()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, HasBitSetters::clusterpoint(this), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mUSV.SensorData)
}

::google::protobuf::uint8* SensorData::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:mUSV.SensorData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .mUSV.SensorData.Pose2D pose = 1;
  if (this->has_pose()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, HasBitSetters::pose(this), target);
  }

  // repeated int32 obstacle_sensors = 2 [packed = true];
  if (this->obstacle_sensors_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _obstacle_sensors_cached_byte_size_.load(std::memory_order_relaxed),
         target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->obstacle_sensors_, target);
  }

  // repeated int32 target_sensors = 3 [packed = true];
  if (this->target_sensors_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _target_sensors_cached_byte_size_.load(std::memory_order_relaxed),
         target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->target_sensors_, target);
  }

  // .google.protobuf.Timestamp timestamp = 4;
  if (this->has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, HasBitSetters::timestamp(this), target);
  }

  // repeated .mUSV.SensorData.Waypoint waypoints = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->waypoints_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->waypoints(static_cast<int>(i)), target);
  }

  // bool loop_waypoints = 6;
  if (this->loop_waypoints() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->loop_waypoints(), target);
  }

  // .mUSV.SensorData.ClusterPoint clusterPoint = 7;
  if (this->has_clusterpoint()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        7, HasBitSetters::clusterpoint(this), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mUSV.SensorData)
  return target;
}

size_t SensorData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mUSV.SensorData)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 obstacle_sensors = 2 [packed = true];
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->obstacle_sensors_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast<::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    _obstacle_sensors_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated int32 target_sensors = 3 [packed = true];
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->target_sensors_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast<::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    _target_sensors_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated .mUSV.SensorData.Waypoint waypoints = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->waypoints_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->waypoints(static_cast<int>(i)));
    }
  }

  // .mUSV.SensorData.Pose2D pose = 1;
  if (this->has_pose()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *pose_);
  }

  // .google.protobuf.Timestamp timestamp = 4;
  if (this->has_timestamp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *timestamp_);
  }

  // .mUSV.SensorData.ClusterPoint clusterPoint = 7;
  if (this->has_clusterpoint()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *clusterpoint_);
  }

  // bool loop_waypoints = 6;
  if (this->loop_waypoints() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SensorData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mUSV.SensorData)
  GOOGLE_DCHECK_NE(&from, this);
  const SensorData* source =
      ::google::protobuf::DynamicCastToGenerated<SensorData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mUSV.SensorData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mUSV.SensorData)
    MergeFrom(*source);
  }
}

void SensorData::MergeFrom(const SensorData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mUSV.SensorData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  obstacle_sensors_.MergeFrom(from.obstacle_sensors_);
  target_sensors_.MergeFrom(from.target_sensors_);
  waypoints_.MergeFrom(from.waypoints_);
  if (from.has_pose()) {
    mutable_pose()->::mUSV::SensorData_Pose2D::MergeFrom(from.pose());
  }
  if (from.has_timestamp()) {
    mutable_timestamp()->::google::protobuf::Timestamp::MergeFrom(from.timestamp());
  }
  if (from.has_clusterpoint()) {
    mutable_clusterpoint()->::mUSV::SensorData_ClusterPoint::MergeFrom(from.clusterpoint());
  }
  if (from.loop_waypoints() != 0) {
    set_loop_waypoints(from.loop_waypoints());
  }
}

void SensorData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mUSV.SensorData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SensorData::CopyFrom(const SensorData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mUSV.SensorData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SensorData::IsInitialized() const {
  return true;
}

void SensorData::Swap(SensorData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SensorData::InternalSwap(SensorData* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  obstacle_sensors_.InternalSwap(&other->obstacle_sensors_);
  target_sensors_.InternalSwap(&other->target_sensors_);
  CastToBase(&waypoints_)->InternalSwap(CastToBase(&other->waypoints_));
  swap(pose_, other->pose_);
  swap(timestamp_, other->timestamp_);
  swap(clusterpoint_, other->clusterpoint_);
  swap(loop_waypoints_, other->loop_waypoints_);
}

::google::protobuf::Metadata SensorData::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_musv_5fmsg_2eproto);
  return ::file_level_metadata_musv_5fmsg_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace mUSV
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::mUSV::RequestData* Arena::CreateMaybeMessage< ::mUSV::RequestData >(Arena* arena) {
  return Arena::CreateInternal< ::mUSV::RequestData >(arena);
}
template<> PROTOBUF_NOINLINE ::mUSV::SensorData_Pose2D* Arena::CreateMaybeMessage< ::mUSV::SensorData_Pose2D >(Arena* arena) {
  return Arena::CreateInternal< ::mUSV::SensorData_Pose2D >(arena);
}
template<> PROTOBUF_NOINLINE ::mUSV::SensorData_Waypoint* Arena::CreateMaybeMessage< ::mUSV::SensorData_Waypoint >(Arena* arena) {
  return Arena::CreateInternal< ::mUSV::SensorData_Waypoint >(arena);
}
template<> PROTOBUF_NOINLINE ::mUSV::SensorData_ClusterPoint* Arena::CreateMaybeMessage< ::mUSV::SensorData_ClusterPoint >(Arena* arena) {
  return Arena::CreateInternal< ::mUSV::SensorData_ClusterPoint >(arena);
}
template<> PROTOBUF_NOINLINE ::mUSV::SensorData* Arena::CreateMaybeMessage< ::mUSV::SensorData >(Arena* arena) {
  return Arena::CreateInternal< ::mUSV::SensorData >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
