# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: musv_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='musv_msg.proto',
  package='mUSV',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0emusv_msg.proto\x12\x04mUSV\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n\x0bRequestData\x12\x0e\n\x06tag_id\x18\x01 \x01(\x05\x12\x19\n\x11request_waypoints\x18\x02 \x01(\x08\"\xc8\x03\n\nSensorData\x12%\n\x04pose\x18\x01 \x01(\x0b\x32\x17.mUSV.SensorData.Pose2D\x12\x34\n\x13nearby_vessel_poses\x18\x02 \x03(\x0b\x32\x17.mUSV.SensorData.Pose2D\x12\x1a\n\x0etarget_sensors\x18\x03 \x03(\x05\x42\x02\x10\x01\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\twaypoints\x18\x05 \x03(\x0b\x32\x19.mUSV.SensorData.Waypoint\x12\x16\n\x0eloop_waypoints\x18\x06 \x01(\x08\x12\x33\n\x0c\x63lusterPoint\x18\x07 \x01(\x0b\x32\x1d.mUSV.SensorData.ClusterPoint\x1a\x45\n\x06Pose2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0b\n\x03yaw\x18\x03 \x01(\x02\x12\x0b\n\x03xpx\x18\x04 \x01(\x05\x12\x0b\n\x03ypx\x18\x05 \x01(\x05\x1a \n\x08Waypoint\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x1a.\n\x0c\x43lusterPoint\x12\r\n\x05range\x18\x01 \x01(\x02\x12\x0f\n\x07heading\x18\x02 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_REQUESTDATA = _descriptor.Descriptor(
  name='RequestData',
  full_name='mUSV.RequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag_id', full_name='mUSV.RequestData.tag_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_waypoints', full_name='mUSV.RequestData.request_waypoints', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=113,
)


_SENSORDATA_POSE2D = _descriptor.Descriptor(
  name='Pose2D',
  full_name='mUSV.SensorData.Pose2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='mUSV.SensorData.Pose2D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='mUSV.SensorData.Pose2D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='mUSV.SensorData.Pose2D.yaw', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xpx', full_name='mUSV.SensorData.Pose2D.xpx', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ypx', full_name='mUSV.SensorData.Pose2D.ypx', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=490,
)

_SENSORDATA_WAYPOINT = _descriptor.Descriptor(
  name='Waypoint',
  full_name='mUSV.SensorData.Waypoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='mUSV.SensorData.Waypoint.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='mUSV.SensorData.Waypoint.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=524,
)

_SENSORDATA_CLUSTERPOINT = _descriptor.Descriptor(
  name='ClusterPoint',
  full_name='mUSV.SensorData.ClusterPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='range', full_name='mUSV.SensorData.ClusterPoint.range', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='mUSV.SensorData.ClusterPoint.heading', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=572,
)

_SENSORDATA = _descriptor.Descriptor(
  name='SensorData',
  full_name='mUSV.SensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose', full_name='mUSV.SensorData.pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nearby_vessel_poses', full_name='mUSV.SensorData.nearby_vessel_poses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_sensors', full_name='mUSV.SensorData.target_sensors', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='mUSV.SensorData.timestamp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='waypoints', full_name='mUSV.SensorData.waypoints', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loop_waypoints', full_name='mUSV.SensorData.loop_waypoints', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clusterPoint', full_name='mUSV.SensorData.clusterPoint', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SENSORDATA_POSE2D, _SENSORDATA_WAYPOINT, _SENSORDATA_CLUSTERPOINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=572,
)

_SENSORDATA_POSE2D.containing_type = _SENSORDATA
_SENSORDATA_WAYPOINT.containing_type = _SENSORDATA
_SENSORDATA_CLUSTERPOINT.containing_type = _SENSORDATA
_SENSORDATA.fields_by_name['pose'].message_type = _SENSORDATA_POSE2D
_SENSORDATA.fields_by_name['nearby_vessel_poses'].message_type = _SENSORDATA_POSE2D
_SENSORDATA.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SENSORDATA.fields_by_name['waypoints'].message_type = _SENSORDATA_WAYPOINT
_SENSORDATA.fields_by_name['clusterPoint'].message_type = _SENSORDATA_CLUSTERPOINT
DESCRIPTOR.message_types_by_name['RequestData'] = _REQUESTDATA
DESCRIPTOR.message_types_by_name['SensorData'] = _SENSORDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestData = _reflection.GeneratedProtocolMessageType('RequestData', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTDATA,
  __module__ = 'musv_msg_pb2'
  # @@protoc_insertion_point(class_scope:mUSV.RequestData)
  ))
_sym_db.RegisterMessage(RequestData)

SensorData = _reflection.GeneratedProtocolMessageType('SensorData', (_message.Message,), dict(

  Pose2D = _reflection.GeneratedProtocolMessageType('Pose2D', (_message.Message,), dict(
    DESCRIPTOR = _SENSORDATA_POSE2D,
    __module__ = 'musv_msg_pb2'
    # @@protoc_insertion_point(class_scope:mUSV.SensorData.Pose2D)
    ))
  ,

  Waypoint = _reflection.GeneratedProtocolMessageType('Waypoint', (_message.Message,), dict(
    DESCRIPTOR = _SENSORDATA_WAYPOINT,
    __module__ = 'musv_msg_pb2'
    # @@protoc_insertion_point(class_scope:mUSV.SensorData.Waypoint)
    ))
  ,

  ClusterPoint = _reflection.GeneratedProtocolMessageType('ClusterPoint', (_message.Message,), dict(
    DESCRIPTOR = _SENSORDATA_CLUSTERPOINT,
    __module__ = 'musv_msg_pb2'
    # @@protoc_insertion_point(class_scope:mUSV.SensorData.ClusterPoint)
    ))
  ,
  DESCRIPTOR = _SENSORDATA,
  __module__ = 'musv_msg_pb2'
  # @@protoc_insertion_point(class_scope:mUSV.SensorData)
  ))
_sym_db.RegisterMessage(SensorData)
_sym_db.RegisterMessage(SensorData.Pose2D)
_sym_db.RegisterMessage(SensorData.Waypoint)
_sym_db.RegisterMessage(SensorData.ClusterPoint)


_SENSORDATA.fields_by_name['target_sensors']._options = None
# @@protoc_insertion_point(module_scope)
